# fly.toml app configuration file generated for welcome-to-js
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "welcome-to-js"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 4005
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[vm]]
  size = 'shared-cpu-1x'
